name: Create Multiarch ChirpStack Network Server Container 

on: 
    push:
    schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
    create-container:
        name: Create Multiarch ChirpStack Network Server Container
        runs-on: ubuntu-latest
        steps:
          - name: Get latest ChirpStack release tag
            id: chirpstack-release
            uses: pozetroninc/github-action-get-latest-release@master
            with:
              repository: brocaar/chirpstack-network-server
              excludes: prerelease, draft
          - name: Check out latest ChirpStack release
            uses: actions/checkout@v2
            with:
                repository: brocaar/chirpstack-network-server
                ref: ${{ steps.chirpstack-release.outputs.release }}

          - name: Modify ChirpStack dockerfile for multiarch builds
            run: |
                 sed -i 's/FROM g/FROM --platform=$BUILDPLATFORM g/' Dockerfile
                 sed -i 's/RUN make/COPY --from=tonistiigi\/xx:golang \/ \/\nARG TARGETPLATFORM\nRUN make/' Dockerfile
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v1
          - name: Set up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v1
          - name: Available platforms
            run: echo ${{ steps.buildx.outputs.platforms }}
          - name: Login to Docker Hub
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}
          - name: Build and push
            uses: docker/build-push-action@v2
            with:
                context: .
                platforms: linux/amd64,linux/arm64,linux/arm/v7
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/chirpstack-network-server:${{ steps.chirpstack-release.outputs.release }}
          